const guides=[
{id:'wholesale',title:'The Wholesale Playbook: Markups, Margins and Buyers',audience:'Professionals',price:50,member:35,pages:48},
{id:'couture',title:'Haute Couture Explained',audience:'Students',price:39,member:27,pages:32},
{id:'career',title:'Your First Role in Luxury: Career Starter Guide',audience:'Students',price:29,member:19,pages:40},
{id:'brand',title:'Building a Fashion Brand: First 12 Months',audience:'Brand Owners',price:59,member:41,pages:56}];
const courses=[{id:'industry',title:'Inside the Luxury Industry',audience:'Students',price:129,lessons:6,duration:'2 hours'}, {id:'professional',title:'From Student to Luxury Professional',audience:'Professionals',price:99,lessons:5,duration:'90 minutes'}, {id:'positioning',title:'Brand Positioning for Fashion Founders',audience:'Brand Owners',price:149,lessons:4,duration:'80 minutes'}];
const sessions=[{id:'assessment',title:'Brand Assessment',duration:60,price:250,description:'Discuss your brand and leave with clear next steps.'},{id:'audit',title:'Brand Audit',duration:90,price:390,description:'Review positioning, product range and your route to market.'},{id:'support',title:'Career Support',duration:45,price:120,description:'Talk through your portfolio, applications and career direction.'}];
let cart=[],purchases=[],bookings=[],plan=null,annual=false,audience='All',sort='featured',booking={},completed={},profile='Alex',lastOrder='';
const app=document.querySelector('#app'),euro=n=>'€'+n,link=(text,route,secondary=false)=>`<a class="btn ${secondary?'secondary':''}" href="#${route}">${text}</a>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const heading=(title,sub='')=>`<div class="hero"><span class="eyebrow">The Luxury Classroom</span><h1>${title}</h1>${sub?`<p>${sub}</p>`:''}</div>`;
const product=id=>[...guides,...courses].find(x=>x.id===id);
function price(x){return plan&&x.member?x.member:x.price}
function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.style.display='none',2600)}
function add(id){if(!cart.includes(id))cart.push(id);document.querySelector('#cart-link').textContent=`Cart (${cart.length})`;toast('Added to cart. Open Cart to continue.')}
function card(x){const course=!!x.lessons;return `<article class="card"><a class="cover ${course?'dark':''}" href="#${course?'course':'guide'}/${x.id}">${x.title}</a><span class="tag">${x.audience}${course?' · Included in Premium':''}</span><h3>${x.title}</h3><p>${course?`${x.lessons} lessons · ${x.duration}`:`PDF guide · ${x.pages} pages`}</p><div class="price">${euro(x.price)}${x.member?`<small>Member price ${euro(x.member)}</small>`:''}</div>${course?link('View course','course/'+x.id):`<button onclick="add('${x.id}')">Add to cart</button>`}</article>`}
function filters(){return `<div class="chips">${['All','Students','Professionals','Brand Owners'].map(a=>`<button class="${audience===a?'active':''}" onclick="audience='${a}';render()">${a}</button>`).join('')}</div>`}
function plans(){return `<div class="chips"><button class="${!annual?'active':''}" onclick="annual=false;render()">Monthly</button><button class="${annual?'active':''}" onclick="annual=true;render()">Annual · save up to 25%</button></div><div class="grid two">${[['Essential',20,180,'Member library<br>Member prices on guides'],['Premium',35,320,'Everything in Essential<br>All video courses<br>Monthly live masterclass']].map(([name,month,year,benefits])=>`<article class="card"><span class="tag">${name==='Premium'?'For continued learning':'Start here'}</span><h3>${name}</h3><div class="price">${euro(annual?year:month)} / ${annual?'year':'month'}</div><p>${benefits}</p>${annual?`<p>Save ${euro(month*12-year)} per year</p>`:''}<button onclick="selectPlan('${name}')">Choose ${name}</button></article>`).join('')}</div>`}
const memberNav=[['Dashboard','dashboard'],['My purchases','purchases'],['Member library','member-library'],['My bookings','bookings'],['Masterclasses','masterclasses'],['Membership & billing','billing'],['Profile settings','profile']];
const adminNav=[['Overview','admin'],['Products editor','products-editor'],['Course builder','course-builder']];
function shell(content,admin=false){return `<div class="layout"><aside class="sidebar"><h3>${admin?'Admin demo':'My classroom'}</h3>${(admin?adminNav:memberNav).map(([t,r])=>`<a class="${location.hash==='#'+r?'selected':''}" href="#${r}">${t}</a>`).join('')}${link(admin?'View student account':'View storefront',admin?'dashboard':'home',true)}</aside><div>${content}</div></div>`}
function selectPlan(name){booking={};window.chosenPlan={name,annual,price:name==='Essential'?(annual?180:20):(annual?320:35)};location.hash='checkout/membership'}
function checkout(kind){const selected=kind==='membership'?window.chosenPlan:kind==='booking'?booking.session:null;if(kind==='membership'&&!selected)return heading('Choose a membership')+link('View plans','membership');if(kind==='booking'&&!selected)return link('Choose a session','consultations');const total=selected?selected.price:cart.reduce((a,id)=>a+price(product(id)),0);if(!selected&&!cart.length)return heading('Your cart is empty')+link('Explore the library','library');return heading('Demo checkout','This simulates payment. Do not enter real payment details.')+`<div class="grid two"><form class="panel" onsubmit="finishOrder(event,'${kind||'cart'}')"><label>Your name<input name="name" required value="${esc(profile)}"></label><label>Email<input type="email" required placeholder="you@example.com"></label><label>Card number<input disabled value="4242 4242 4242 4242 · Test card"></label><div class="grid two"><label>Expiry<input disabled value="12 / 30"></label><label>CVC<input disabled value="123"></label></div><button>Simulate payment · ${euro(total)}</button></form><div class="panel"><h2>Order summary</h2>${selected?`<p>${esc(selected.name||selected.title)}</p>${kind==='booking'?`<p>${booking.date} · ${booking.time}<br>Dubai time, UTC+4</p>`:`<p>Billed ${selected.annual?'annually':'monthly'}</p>`}`:cart.map(id=>`<p>${product(id).title} <strong>${euro(price(product(id)))}</strong></p>`).join('')}<hr><h3>Total ${euro(total)}</h3><p>${plan?'Member prices applied to guides.':'Have a membership? Choose a plan to try member prices.'}</p></div></div>`}
function finishOrder(event,kind){event.preventDefault();profile=new FormData(event.target).get('name');if(kind==='membership'){plan=window.chosenPlan;lastOrder=`Your ${plan.name} membership is active in this demo.`}else if(kind==='booking'){bookings.push({...booking});lastOrder=`${booking.session.title} booked for ${booking.date} at ${booking.time}, Dubai time.`;booking={}}else{purchases=[...new Set([...purchases,...cart])];cart=[];lastOrder='Your purchase is ready in My purchases.'}location.hash='confirmation'}
function render(){const [route='home',id]=location.hash.slice(1).split('/');let content='';document.querySelector('#cart-link').textContent=`Cart (${cart.length})`;
if(route==='home'){content=heading('Learn luxury from the inside.','Practical guides, courses and personal advice from David, a luxury professional and fashion lecturer.')+`<div class="row">${link('Explore the library','library')}${link('Become a member','membership',true)}</div><section class="space"><div class="section-head"><h2>Guides for your next step</h2><a href="#library">View all guides</a></div>${filters()}<div class="grid four">${guides.filter(x=>audience==='All'||x.audience===audience).map(card).join('')}</div></section><section><h2>Learn at your own pace</h2><div class="grid">${courses.map(card).join('')}</div></section><section><h2>A membership that grows with you</h2>${plans()}</section><section><h2>Work with David, one to one</h2><div class="grid">${sessions.map(s=>`<div class="card"><h3>${s.title}</h3><p>${s.duration} minutes · ${euro(s.price)}</p>${link('Book a session','book/'+s.id)}</div>`).join('')}</div></section><div class="band"><span class="tag">Premium members · 15 October 2026 · 18:00 Dubai</span><h2>How Luxury Buyers Choose New Brands</h2>${link('View masterclasses','masterclasses')}</div><section><h2>Meet David</h2><p>20 years of experience in fashion and luxury, brought into the classroom. Learn how the industry works beyond the textbook.</p>${link('Read my story','about',true)}</section>`}
else if(route==='library'||route==='courses'){let list=route==='library'?guides:courses;list=list.filter(x=>audience==='All'||x.audience===audience);if(sort==='low')list=[...list].sort((a,b)=>a.price-b.price);content=heading(route==='library'?'The library':'Courses',route==='library'?'Practical guides to keep and refer back to.':'Learn how the industry works, one lesson at a time.')+filters()+`<label style="max-width:220px">Sort by<select onchange="sort=this.value;render()"><option value="featured">Featured</option><option value="low" ${sort==='low'?'selected':''}>Price: low to high</option></select></label><div class="grid ${route==='library'?'four':''}">${list.map(card).join('')}</div><div class="notice">Member-only reading is available in the <a href="#member-library">Member library</a>.</div>`}
else if(route==='guide'||route==='course'){const x=product(id);if(!x){content=heading('Item not found')}else{const course=route==='course';content=`<p><a href="#${course?'courses':'library'}">← Back to ${course?'courses':'library'}</a></p><div class="grid two"><div>${course?`<div class="video"><div>Course introduction<p>Video placeholder</p>${link('Open free preview','lesson/'+x.id+'/1')}</div></div>`:`<div class="cover dark" style="min-height:320px;font-size:35px">${x.title}</div>`}</div><div><span class="tag">${x.audience}</span><h1>${x.title}</h1><p>${course?'A practical introduction with short lessons and examples you can apply.':'A practical reference with industry examples, checklists and questions to guide your next steps.'}</p><div class="price">${euro(x.price)}${x.member?`<small>Member price ${euro(x.member)} · <a href="#membership">Become a member</a></small>`:'<small>Included in Premium membership</small>'}</div><div class="row"><button onclick="add('${x.id}')">${course?'Buy course':'Add to cart'}</button>${course&&plan?.name==='Premium'?link('Start learning','lesson/'+x.id+'/1'):link('Buy now','buy/'+x.id,true)}</div></div></div><section class="space"><h2>${course?"What you'll learn":"What's inside"}</h2><ul><li>How the industry works in practice</li><li>Common mistakes and how to avoid them</li><li>A checklist for your next steps</li></ul>${course?`<h2>Lessons</h2><ul class="list">${Array.from({length:x.lessons},(_,i)=>`<li><a href="#lesson/${x.id}/${i+1}">${i+1}. ${lessonTitle(i)} · ${i===0?'Free preview':'Locked until enrolled'}</a></li>`).join('')}</ul>`:`<p>${x.pages} pages · PDF download after purchase</p>`}</section>`}}
else if(route==='buy'){add(id);location.hash='checkout';return}
else if(route==='membership'){content=heading('Make learning a habit.','Choose the access you need. All prices are placeholders.')+plans()+`<section class="space table-wrap"><table><tr><th>Included</th><th>Essential</th><th>Premium</th></tr><tr><td>Member library and guide discounts</td><td>Yes</td><td>Yes</td></tr><tr><td>All video courses</td><td>Buy separately</td><td>Yes</td></tr><tr><td>Monthly masterclasses</td><td>No</td><td>Yes</td></tr><tr><td>1:1 consultations</td><td>Separate purchase</td><td>Separate purchase</td></tr></table></section><h2>Membership questions</h2><details><summary>Can I cancel anytime?</summary><p>Yes. Access continues until the end of the paid period.</p></details><details><summary>What happens to downloads?</summary><p>Purchased guides are yours to keep. Member-only guides are read online while your membership is active.</p></details>`}
else if(route==='consultations'){content=heading('A conversation about your next step.','Choose the session that fits your career or brand.')+`<div class="grid">${sessions.map(s=>`<article class="card"><h3>${s.title}</h3><p>${s.description}</p><div class="price">${euro(s.price)}<small>${s.duration} minutes · Online</small></div>${link('Book a session','book/'+s.id)}</article>`).join('')}</div>`}
else if(route==='book'){const s=sessions.find(x=>x.id===id)||sessions[0];content=heading('Book '+s.title,'1. Session → 2. Date & details → 3. Demo payment → 4. Confirmation')+`<form class="panel narrow" onsubmit="bookSession(event,'${s.id}')"><h2>${s.duration} minutes · ${euro(s.price)}</h2><p>All times shown in Dubai time, UTC+4. Availability is sample data.</p><label>Available date<select name="date"><option>2026-10-06</option><option>2026-10-08</option><option>2026-10-13</option></select></label><label>Available time<select name="time"><option>10:00</option><option>14:00</option><option>16:00</option></select></label><label>What would you like to discuss?<textarea name="notes" required></textarea></label><button>Continue to payment</button></form>`}
else if(route==='cart'){content=heading('Your cart')+(cart.length?`<div class="panel">${cart.map(id=>`<div class="section-head"><p>${product(id).title} · <strong>${euro(price(product(id)))}</strong></p><button class="secondary small" onclick="cart=cart.filter(x=>x!=='${id}');render()">Remove</button></div>`).join('')}<hr><h2>Total ${euro(cart.reduce((a,id)=>a+price(product(id)),0))}</h2>${link('Continue to checkout','checkout')}</div>`:`<p>Your cart is empty.</p>${link('Browse guides','library')}`)}
else if(route==='checkout'){content=checkout(id)}
else if(route==='confirmation'){content=heading('You’re all set.',lastOrder)+`<div class="notice">Demo confirmation. No payment was taken and no email was sent.</div><div class="row">${link('Go to my classroom','dashboard')}${link('View purchases','purchases',true)}${link('My bookings','bookings',true)}</div>`}
else if(['login','signup','forgot'].includes(route)){content=heading(route==='signup'?'Create your account':route==='forgot'?'Reset your password':'Welcome back')+`<form class="panel narrow" onsubmit="account(event,'${route}')"><p>Demo account. Use any example email and password.</p>${route==='signup'?'<label>Name<input name="name" required></label>':''}<label>Email<input type="email" required></label>${route!=='forgot'?'<label>Password<input type="password" required minlength="4"></label>':''}<button>${route==='forgot'?'Simulate reset email':route==='signup'?'Create demo account':'Enter demo account'}</button><p><a href="#signup">Create an account</a> · <a href="#forgot">Forgot password?</a> · <a href="#login">Login</a></p></form>`}
else if(route==='dashboard'){content=shell(heading('Welcome, '+esc(profile), 'Your learning and bookings in one place.')+`<div class="grid two"><div class="panel"><h3>Continue learning</h3><p>Inside the Luxury Industry</p><progress max="6" value="${(completed.industry||[]).length}"></progress><p>${(completed.industry||[]).length} of 6 lessons complete</p>${link('Open course','lesson/industry/1')}</div><div class="panel"><h3>Membership</h3><p>${plan?plan.name+' · '+(plan.cancelled?'Ends after this period':'Active'):'No active membership'}</p>${link(plan?'Manage membership':'View plans',plan?'billing':'membership',true)}</div><div class="panel"><h3>Next booking</h3><p>${bookings.length?esc(bookings[0].session.title)+' · '+bookings[0].date:'No upcoming bookings'}</p>${link('View bookings','bookings',true)}</div><div class="panel"><h3>Next masterclass</h3><p>15 October · How Luxury Buyers Choose New Brands</p>${link('View masterclass','masterclasses',true)}</div></div>`)}
else if(route==='purchases'){content=shell(heading('My purchases')+(purchases.length?`<div class="grid two">${purchases.map(id=>{const x=product(id);return `<div class="card"><h3>${x.title}</h3><p>${x.lessons?'Course access':'Purchased PDF guide'}</p>${x.lessons?link('Start learning','lesson/'+id+'/1'):`<button onclick="downloadSample('${id}')">Download sample</button>`}</div>`}).join('')}</div>`:`<p>No purchases yet. Complete a demo checkout to see your purchases here.</p>${link('Explore the library','library')}`))}
else if(route==='member-library'){content=shell(heading('Member library','Read online with an active membership.')+(plan?`<div class="grid two">${['Luxury retail field notes','A buyer’s seasonal checklist'].map((t,i)=>`<div class="card"><span class="tag">Members only · Read online</span><h3>${t}</h3>${link('Open reader','reader/'+i)}</div>`).join('')}</div>`:link('Choose a membership','membership')))}
else if(route==='reader'){content=shell(plan?`<p><a href="#member-library">← Member library</a></p><article class="panel narrow"><span class="tag">Sample reading · Page 1 of 1</span><h1>${id==='0'?'Luxury retail field notes':'A buyer’s seasonal checklist'}</h1><p>Start with the customer. What brings them into the store, and what do they need to know before making a decision?</p><h2>Try this</h2><p>Visit a store and note how the team introduces the collection, explains materials and answers questions about value.</p><p>This is placeholder content for the in-browser member reader.</p></article>`:link('Choose a membership','membership'))}
else if(route==='lesson'){const x=courses.find(x=>x.id===id)||courses[0],n=Number(location.hash.split('/')[2]||1),allowed=n===1||plan?.name==='Premium'||purchases.includes(x.id);content=shell(`<h1>${x.title}</h1><div class="grid two"><div><div class="video"><div>${allowed?`Lesson ${n} · ${lessonTitle(n-1)}<p>Video placeholder. No streaming in this draft.</p>`:`This lesson is locked.<p>Buy the course or join Premium.</p>${link('View course','course/'+x.id)}`}</div></div>${allowed?`<p>Sample lesson notes and practical examples will appear here.</p><button onclick="completeLesson('${x.id}',${n})">${(completed[x.id]||[]).includes(n)?'Completed ✓':'Mark as complete'}</button> ${n<x.lessons?link('Next lesson','lesson/'+x.id+'/'+(n+1),true):link('Back to dashboard','dashboard',true)}`:''}</div><div class="panel"><h3>Lessons</h3><progress max="${x.lessons}" value="${(completed[x.id]||[]).length}"></progress><ul class="list">${Array.from({length:x.lessons},(_,i)=>`<li><a href="#lesson/${x.id}/${i+1}">${(completed[x.id]||[]).includes(i+1)?'✓ ':''}${i+1}. ${lessonTitle(i)} ${i===0?'· Free preview':''}</a></li>`).join('')}</ul></div></div>`)}
else if(route==='bookings'){content=shell(heading('My bookings')+(bookings.length?bookings.map(b=>`<div class="panel"><h3>${b.session.title}</h3><p>${b.date} · ${b.time} · Dubai time, UTC+4</p><button onclick="toast('A real meeting link will appear here after booking.')">Join meeting · demo</button></div>`).join(''):`<p>No upcoming sessions.</p>${link('Book a session','consultations')}`)+`<h2>Past sessions</h2><p>No past sessions.</p>`)}
else if(route==='masterclasses'){content=shell(heading('Monthly masterclasses')+`<div class="panel"><span class="tag">Premium members</span><h2>How Luxury Buyers Choose New Brands</h2><p>15 October 2026 · 18:00 Dubai time, UTC+4</p>${plan?.name==='Premium'?'<button onclick="toast(\'The live session link will become available on the day.\')">Join · demo</button>':link('Join Premium','membership')}</div><h2>Past recordings</h2><div class="panel"><h3>Understanding the luxury customer</h3>${plan?.name==='Premium'?link('Open sample recording','recording'):link('Unlock with Premium','membership')}</div>`)}
else if(route==='recording'){content=shell(plan?.name==='Premium'?heading('Understanding the luxury customer')+'<div class="video">Sample recording placeholder</div>':link('Join Premium','membership'))}
else if(route==='billing'){content=shell(heading('Membership & billing')+(plan?`<div class="panel"><h2>${plan.name}</h2><p>${euro(plan.price)} / ${plan.annual?'year':'month'} · ${plan.cancelled?'Cancelled, access until period end':'Active'}</p><p>${plan.cancelled?'Access ends':'Renews'}: ${plan.annual?'22 September 2027':'22 October 2026'} · Example date</p><div class="row">${link('Change plan','membership')}<button class="secondary" onclick="plan.cancelled=!plan.cancelled;render()">${plan.cancelled?'Resume membership':'Cancel renewal'}</button></div></div><h2>Invoices</h2><p>Demo membership order · ${euro(plan.price)} · Paid</p>`:`<p>You do not have an active membership.</p>${link('View plans','membership')}`))}
else if(route==='profile'){content=shell(heading('Profile settings')+`<form class="panel" onsubmit="event.preventDefault();profile=new FormData(this).get('name');toast('Profile saved for this demo.');render()"><label>Name<input name="name" value="${esc(profile)}" required></label><label>Email<input type="email" value="alex@example.com" required></label><label>Audience<select><option>Student</option><option>Professional</option><option>Brand owner</option></select></label><button>Save profile</button></form>`)}
else if(route==='about'){content=heading('Meet David','20 years in fashion and luxury. Now sharing that experience with the next generation.')+`<div class="grid two"><div class="cover" style="min-height:260px">David’s portrait will go here</div><div><h2>Experience behind the lessons</h2><p>David is a fashion and luxury professional and a lecturer at a fashion academy in Dubai. The Luxury Classroom brings his practical industry knowledge into guides, courses and one-to-one conversations.</p><p>Full biography, career dates and project examples to be supplied by David.</p><div class="row">${link('Become a member','membership')}${link('Book a consultation','consultations',true)}</div></div></div><h2>Career highlights</h2><p>Fashion and luxury industry experience → Teaching in Dubai → The Luxury Classroom</p><h2>Projects, interviews and celebrity work</h2><p>Approved projects, interview links and photographs will be added here.</p>`}
else if(route==='admin'){content=shell(heading('Admin overview','Sample figures for the platform owner.')+`<div class="grid"><div class="panel"><span class="tag">Sales this month</span><h2>€2,480</h2></div><div class="panel"><span class="tag">Active members</span><h2>64</h2></div><div class="panel"><span class="tag">Upcoming bookings</span><h2>${bookings.length+3}</h2></div></div><h2>Recent orders · sample</h2><div class="table-wrap"><table><tr><th>Customer</th><th>Product</th><th>Total</th><th>Status</th></tr><tr><td>Alex Morgan</td><td>Premium monthly</td><td>€35</td><td>Paid</td></tr><tr><td>Sam Taylor</td><td>Wholesale Playbook</td><td>€50</td><td>Paid</td></tr></table></div><div class="row space">${link('Manage guides','products-editor')}${link('Build a course','course-builder',true)}</div>`,true)}
else if(route==='products-editor'){content=shell(heading('Products editor','Sample editor. Uploads are simulated.')+`<form class="panel" onsubmit="event.preventDefault();toast('Demo product saved. No files were uploaded.')"><label>Product title<input required value="The Wholesale Playbook"></label><div class="grid two"><label>Cover image<input type="file" accept="image/*"></label><label>PDF file<input type="file" accept="application/pdf"></label></div><label>Description<textarea>A practical guide to wholesale, margins and buyers.</textarea></label><div class="grid two"><label>Price (€)<input type="number" min="0" value="50" required></label><label>Member price (€)<input type="number" min="0" value="35" required></label><label>Audience<select><option>Professionals</option><option>Students</option><option>Brand Owners</option></select></label><label>Visibility<select><option>Both</option><option>Purchasable</option><option>Members only</option></select></label></div><button>Simulate save</button></form>`,true)}
else if(route==='course-builder'){content=shell(heading('Course builder','Edit course details and reorder the sample lessons.')+`<form class="panel" onsubmit="event.preventDefault();toast('Demo course saved. No files were uploaded.')"><label>Course title<input value="Inside the Luxury Industry" required></label><label>Description<textarea>An introduction to luxury and the people behind it.</textarea></label><label>Price (€)<input type="number" min="0" value="129" required></label><h3>Lessons</h3><div id="editor-lessons">${[1,2,3].map((n)=>`<div class="panel"><label>Lesson title<input value="${lessonTitle(n-1)}"></label><label>Video upload<input type="file" accept="video/*"></label><label><input type="checkbox" ${n===1?'checked':''}> Free preview</label><button type="button" class="secondary small" onclick="moveLesson(this,-1)">Move up</button> <button type="button" class="secondary small" onclick="moveLesson(this,1)">Move down</button></div>`).join('')}</div><button class="space">Simulate save</button></form>`,true)}
else if(route==='map'){content=heading('Explore the draft','Choose a flow. Everything uses sample data and resets when you refresh.')+`<div class="grid"><div class="panel"><h2>Visitor</h2><ol><li><a href="#home">Homepage</a></li><li><a href="#library">Browse guides</a> / <a href="#courses">Courses</a></li><li><a href="#cart">Cart and checkout</a></li><li><a href="#membership">Choose membership</a></li><li><a href="#consultations">Book a consultation</a></li><li><a href="#login">Login / sign up</a></li><li><a href="#about">About David</a></li></ol></div><div class="panel"><h2>Student / member</h2><ul class="list">${memberNav.map(([t,r])=>`<li><a href="#${r}">${t}</a></li>`).join('')}</ul><a href="#lesson/industry/1">Lesson player</a></div><div class="panel"><h2>Platform owner</h2><ul class="list">${adminNav.map(([t,r])=>`<li><a href="#${r}">${t}</a></li>`).join('')}</ul></div></div>`}
else if(['terms','privacy','refund'].includes(route)){content=heading({terms:'Terms',privacy:'Privacy policy',refund:'Refund policy'}[route])+'<p>Policy placeholder. Final policy text will be added before launch.</p>'}
else{content=heading('Page not found')+link('Back home','home')}
app.innerHTML=content;document.title=(app.querySelector('h1')?.textContent||'The Luxury Classroom')+' | Draft';}
function lessonTitle(i){return ['Welcome to the luxury industry','Understanding the customer','How brands create value','Inside a buying decision','Careers and opportunities','Your next steps'][i]||'Course lesson'}
function bookSession(event,id){event.preventDefault();const data=new FormData(event.target);booking={session:sessions.find(s=>s.id===id),date:data.get('date'),time:data.get('time'),notes:data.get('notes')};location.hash='checkout/booking'}
function account(event,route){event.preventDefault();if(route==='forgot'){toast('Demo reset email requested. No email was sent.');return}profile=new FormData(event.target).get('name')||profile;location.hash='dashboard'}
function completeLesson(id,n){completed[id]=[...new Set([...(completed[id]||[]),n])];render()}
function moveLesson(button,direction){const row=button.closest('.panel'),sibling=direction<0?row.previousElementSibling:row.nextElementSibling;if(sibling)direction<0?row.parentNode.insertBefore(row,sibling):row.parentNode.insertBefore(sibling,row)}
function downloadSample(id){const blob=new Blob([product(id).title+'\n\nSample guide download. The final product will be a PDF.\n\n1. Understand your customer.\n2. Review your positioning.\n3. Plan your next steps.'],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=id+'-sample.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0)});render();
